dependencies:
# - <organization/repo>@<version>
- smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    # version: 0.6.6
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
dotenv: .env
networks:
  default: development
  mainnet-fork-dev: 
    eth_usd_price_feed: 0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419
    verify: False
  development:
    verify : False
  ganache-local:
    verify: False
wallets: 
  from_key: ${PRIVATE_KEY}